name: Empacotar extensao (.zip)

on:
  push:
    branches:
      - main

jobs:
  build-upload-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Instalar web-ext
        run: npm install --global web-ext

      - name: Empacotar extensao como .zip
        id: build
        run: web-ext build --source-dir=. --artifacts-dir=build --overwrite-dest

      - name: Get generated zip filename
        id: get_zip_name
        run: |
          ZIP_FILE=$(find build -name "*.zip" -print -quit)
          ZIP_FILENAME=$(basename "$ZIP_FILE")
          echo "zip_filename=$ZIP_FILENAME" >> $GITHUB_OUTPUT

      - name: Listar arquivos gerados
        run: ls -lh build

      # - name: Disponibilizar como artefato
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ steps.get_zip_name.outputs.zip_filename }}
      #     path: build/*.zip
      #     overwrite: true

      - name: Disponibilizar como release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.zip
