name: Empacotar extensao (.zip)

on:
  push:
    branches:
      - main

jobs:
  build-upload-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Instalar web-ext
        run: npm install --global web-ext

      - name: Empacotar extensao como .zip
        id: build
        run: web-ext build --source-dir=. --artifacts-dir=build --overwrite-dest

      - name: Get generated zip filename
        id: get_zip_name
        run: |
          ZIP_FILE=$(find build -name "*.zip" -print -quit)
          ZIP_FILENAME=$(basename "$ZIP_FILE")
          echo "zip_filename=$ZIP_FILENAME" >> $GITHUB_OUTPUT

      - name: Ler versao do manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # - name: Disponibilizar como artefato
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ steps.get_zip_name.outputs.zip_filename }}
      #     path: build/*.zip
      #     overwrite: true

      # - name: Criar tag automaticamente
      #   uses: butlerlogic/action-autotag@stable
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     strategy: regex
      #     file: manifest.json
      #     regex_pattern: '"version":\\s*"([0-9]+\\.[0-9]+\\.[0-9]+)"'

      # - name: Criar release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: build/*.zip
      #     tag_name: ${{ steps.get_version.outputs.version }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/*.zip
          tag: ${{ steps.get_version.outputs.version }}
