name: Empacotar extensão Firefox (.zip)

on:
  push:
    branches:
      - main

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar web-ext
        run: npm install --global web-ext

      - name: Empacotar extensão como .zip
        id: build
        run: |
          web-ext build \
            --source-dir=. \
            --artifacts-dir=build \
            --overwrite-dest
      - name: Listar arquivos gerados
        run: ls -l build

      - name: Upload do artefato .zip
        uses: actions/upload-artifact@v4
        with:
          name: organizador-firefox-zip
          path: build/*.zip
